apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.hyperfleet-sentinel-chart.applicationName }}
  namespace: {{ .Values.hyperfleet-sentinel-chart.namespace }}
spec:
  project: {{ .Values.hyperfleet-sentinel-chart.project }}

  source:
    repoURL: {{ .Values.hyperfleet-sentinel-chart.source.repoURL }}
    targetRevision: {{ .Values.hyperfleet-sentinel-chart.source.targetRevision }}
    path: {{ .Values.hyperfleet-sentinel-chart.source.path }}
    {{- if .Values.hyperfleet-sentinel-chart.values }}
    helm:
      valuesObject:
        {{- toYaml .Values.hyperfleet-sentinel-chart.values | nindent 8 }}
    {{- end }}

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.hyperfleet-sentinel-chart.targetNamespace }}

  syncPolicy:
    {{- if .Values.hyperfleet-sentinel-chart.syncPolicy.automated }}
    automated:
      prune: {{ .Values.hyperfleet-sentinel-chart.syncPolicy.automated.prune }}
      selfHeal: {{ .Values.hyperfleet-sentinel-chart.syncPolicy.automated.selfHeal }}
    {{- end }}
    {{- if .Values.hyperfleet-sentinel-chart.syncPolicy.syncOptions }}
    syncOptions:
      {{- range .Values.hyperfleet-sentinel-chart.syncPolicy.syncOptions }}
      - {{ . }}
      {{- end }}
    {{- end }}
